* ui网站开发建议
我看了一下这两个网站，就先讨论一下90设计网，我粗略看了一下，他们的服务大概有首页展示的页面的效果、搜索的展示和多级的搜索、还有网点服务、功能上还有第三方qq微信登录，qq客服，支持运营的还要有后台最基本的要有上传图片，图片排序的功能，这些功能实际上还算比较多的，我做的话可以是可以，也是抽时间，需要时间一个一个做出来，如果评估时间的话，也需要先研究一下，可以预估个开发的时间，。

我的想法是这样，如果做，就把这个东西当个项目来认真做。咱们先研究这个东西做出来的可行性，提前有个规划，也有个市场行情的预判，分析一下付出和收益，分析一下风险，推广的成本，百度搜索优化那块我暂不太了** (add-hook 'org-mode-hook (lambda () (setq truncate-lines nil)))解，除了竞价排名（好像挺贵的）也有些其他的方法，你可以研究一下，。

做出来网站了没人访问也是个问题，我前面做的项目的老板没有提前考虑好，就遇到过这个问题。另外我有些疑问，这些素材从哪里来找？找的话一些好的图片现在好像也有版权问题，是不能买的。一个一个找素材你一个人的话我觉得工作量可能挺大的。找好图片慢慢排版让页面好看也是个技术活。要和人家竞争，换得考虑怎么变现我觉得也有难度。

另外我有个想法：我给你个人建一个网站，你可以找一些好的素材或者作品再加工，或者自己设计一些好的作品放在网站上，页面的效果就像这样，你设计个ui图，我给你技术实现，你然后你，慢慢设计作品发上去，你的网站页面的静态效果你可以设计，动画效果、功能效果我给你实现，你在慢慢推广，是个细水长流的活，我还觉得挺好的

* 联想维修 网点
地址：西安市建设东路55号（周六可接收送修，法定假日除外）
电话：029-85516223/029－85516229
* 方

** 症
畏寒 走一段路腿疼
不渴
胸闷气短
** 开方
黄芩泻白散合黛蛤散

黄岑10克 桑白皮15克  地骨皮15克  粳米15克   
麦冬10克 北沙参10克 栀子5克 郁金3克 柴胡3克 甘草3克  

http://yibian.hopto.org/fang/?fno=204
http://www.baike.com/wiki/%E9%BB%9B%E8%9B%A4%E6%95%A3
http://www.zysj.com.cn/zhongyaocai/yaocai_z/zhizi.html

http://www.360doc.com/content/15/0702/05/6851991_482048129.shtml

黛蚵散比例
黛蛤散中海蛤壳性味咸寒，可清热化痰、软坚散结，青黛性味咸寒，可清热解毒，凉血定惊，故合用可治疗肝火犯肺，
咳痰带血，咽喉不适等症状，对咳嗽时间比较长，并且痰黏不容易咳出来者尤为有效。一般蛤粉与青黛的配伍比例为10︰1，
热象重者青黛可以酌加，散剂每服3~6g，日服2~3次，煎剂10~30g，儿童酌减。脾胃虚寒者慎用。我的体会直接吞服散剂较煎剂效佳
http://blog.sina.com.cn/s/blog_58d372a70102vuoe.html

-- 小青龙汤 记得李可老中医 用此方加减来治慢性肺病

参考 祛湿利水经典方剂五苓散 https://mp.weixin.qq.com/s?__biz=MzA5ODM0ODgzMA==&mid=2651213214&idx=1&sn=a5feb911b725a4f2369df0143f8a871f&pass_ticket=YTrv83NFiSc592lZ4Vac%2B7lzpE6qjykYG627dLTfZfMh2ZJvyaZ2wZy9w2NunkQV

三、胃苓汤（《丹溪心法》）为五苓散与平胃散（陈皮、厚朴、苍术、甘草）的合方，利水祛湿剂与芳香化湿剂合用，除加强祛湿作用外，还着重加强行气化气作用，适用于脾湿气滞、消化不良、脘腹胀痛泄泻、小便短少者。

查厚朴 
http://yibian.hopto.org/yao/?yno=241 
痰飲喘咳。本品能燥濕化痰，下氣平喘。對於宿有喘病，因外感風寒而發者，可與桂枝、杏仁等同用，如桂枝加厚朴杏子湯；若痰濕內阻，胸悶喘咳者，常與蘇子、橘皮等同用，如蘇子降氣湯。

内科不治喘，治喘丢了脸——经方泰斗胡希恕治哮喘经验总结 http://mp.weixin.qq.com/s/49GHtxN3ZEfhgTkQ-uRl2Q

从六经辨证来看，哮喘常表现为太阳病或少阳病，尤以太阳少阳并病、少阳阳明并病和三阳并病为最多见，而且以实证为多见。中医所说的哮喘，一般多是指临床上的一个症状，以邪气实多见。

大柴胡汤合桂枝茯苓丸方证主症见：胸胁苦满，呼吸困难，心下急，口苦咽千，大便干燥。

少阳病 https://zh.wikipedia.org/wiki/%E5%B0%91%E9%99%BD%E7%97%85
查得 变证 阴阳升降失常，上热下寒证：黄连汤 http://yibian.hopto.org/fang/?fno=95
【辨證要點】
胸中煩熱。
腹中冷痛。
嘔吐下利腸鳴。
苔白膩。
脈弦。

黃連9克  甘草9克  乾薑9克  桂枝9克  人參6克  半夏12克  大棗4枚 

郝万山讲《伤寒论》 第38讲 http://www.theqi.com/simplified/cmed/class/class1/note_38.html
如果全身的表现是无汗的，还可以用麻黄汤，就是完全是寒邪闭郁了阳明经表的阳气，全身表现为无汗，而额头疼痛，缘缘面赤，目痛鼻干，这种症状又不特别突出，那就用麻黄汤

麻黄汤 http://yibian.hopto.org/shu/?sid=603
发汗猛 暂不用

大柴胡湯	 http://yibian.hopto.org/fang/?fno=10

柴胡15克(8兩)  黃芩9克(3兩)  半夏9克(半升) 洗  枳實9克(4枚) 炙  大黃6克(2兩)  芍藥9克(3兩)  生薑15克(5兩) 切  大棗12枚 擘  
右七味，以水一斗二升，煮取六升，去滓再煎，溫服一升，日三服

桂枝茯苓丸 http://yibian.hopto.org/fang/?fno=165
桂枝10克  茯苓10克  牡丹皮10克  白芍10克  桃仁10克  

[经典] 黄煌 大柴胡汤的方证及其现代应用 http://blog.sina.com.cn/s/blog_73b391c60102very.html
先说说大柴胡汤的配方，比起当下一些中医开的方，大柴胡汤算是个小方了，共八味药。柴胡半斤、黄芩三两、半夏半升、枳实四枚、芍药三两、大黄二两，生姜五两、大枣十二枚，以水一斗二升，煮取六升，去滓，再煎。温服一升，日三服。这里有几点说明一下：
柴胡半斤，就是八两，如果按一两等于3克折算，应该24克，如果一两等于5克折算，也应该40克，显然，用柴胡5克10克的，可能算不上大柴胡汤；
 
半夏半升：经推测，半夏一升为五两，半升为二两半，可折算为12.5克，我多用10-15克。
 
枳实四枚：汉代没有枳壳枳实之分，后来将小嫩的果实为枳实，大的为枳壳。这个说法，在宋代沈括《梦溪笔谈》中已经提及。根据实测，一枚枳实重约3克，一枚枳壳重量约为枳实的3-5倍，甚至更多，所以，原方用4枚枳实，可能重量当在40克以上，甚至到80克。提示我们现在用量比较保守，可以摸索大剂量枳实枳壳应用的经验

郝万山讲《伤寒论》
第21讲 太阳蓄血证（1） http://www.theqi.com/cmed/class/class1/note_21.html
大柴胡汤证是上腹部满痛，大承气汤证是脐周极其胀满有力，桃核承气汤证是下腹部压痛。

原来有血管瘤，现在怎么没有呢？对照起来，前后差了半年，就是没有了。他就问怎么治疗的？她说我就是找一个中医大夫，一直吃一种胶囊治好的，但是从那时候到现在，用抵当汤做成散剂治疗脑血管瘤，有这么好的效果的我只遇到这么一例，后来我遇到类似的病人，我也用过，也许是病人在坚持吃药方面，有些困难

“太阳病身黄”，这个身黄，可以见于太阳蓄水，也可以见于太阳蓄血，太阳蓄血，血热互结，阻滞气机，而全身的气机是靠肝胆来疏泄的，血热互结，阻滞气机，气机阻滞以后，就容易反过来影响肝胆疏泄，

是蓄血的，你可以用抵当汤来治疗。这一条特别强调了蓄水和蓄血的区别，在于小便利和小便不利

大柴胡湯 用量 http://www.tcmforum.com/forum2.php?forumID=100483&fGroup=expert

按之心下滿痛者，此為實也，當下之，宜大柴胡湯”。細與《傷寒論》條文對照，可知大柴胡湯證不必非是由太陽而少陽陽明，也可以是雜病獨立的病證。心下者，心之下也，不僅包括胃，也包括肝膽和胰，按之滿痛是點明的主證，其它尚有發熱口燥、惡心、嘔吐、尿赤、大便乾結，或黃疸、胸脅滿痛，舌必紅，苔必黃，脈必沉實滑數。

不過需要指出，在急腹症的治療中，因邪實是主要矛盾，故藥量宜大，如柴胡常用至30克，黃芩15克，大黃30~40克，白芍25克，枳實(或枳殼)15~20克，使藥能勝病，邪去而元氣自復

桃核承氣湯	http://yibian.hopto.org/fang/?fno=161

经方一百首

067、桃核承气汤 与、抵当汤、桂枝茯苓区别
http://www.tcm100.com/user/jfybs/zzbook67.htm
本方与桂枝茯苓丸都有少腹疼痛拒按的瘀血证候、但本方有明显的精神症状，表现小躁、狂、烦的外在征象，是瘀血初聚结；桂枝茯苓丸证偏向于—种安静的状态，瘀血瘀积已久，形成有限范围的癥块。
龙野一雄曾把桃核承气汤、抵当汤、桂枝茯苓丸在腹证进行了详细区别。此三者在腹诊上必须非常熟练才能鉴别。其要点如下：三者的抵抗位置皆无特征，随处可以发现一至数处。
而抵当汤证的抵抗在深部，且略有硬感，无腹动。桂枝茯苓丸证的抵抗亦在深部有硬感，境界多相当明显，亦有成为硬结者，多能证明髂总动脉的紧张、压痛，搏动亢进。桃核承气汤证之抵抗略软，境界多不明显，
虽有髂动脉的紧张和压痛，不一定有搏动亢进的现象，但可见少腹急结。桃核承气汤的加味药多为蒲黄、当归、牛膝、乌药等。本方证病在下焦，故其服法仲景条文提出“先食温服”，以使药力直达病所，迅速发挥逐瘀下行之力。临床使用时多嘱咐病人在饭前1小时空腹服药，应注意

脾陽虛主要是怕冷脾氣虛主要是無力 http://chenron.pixnet.net/blog/post/351714137-%E8%84%BE%E9%99%BD%E8%99%9B%E4%B8%BB%E8%A6%81%E6%98%AF%E6%80%95%E5%86%B7-%E8%84%BE%E6%B0%A3%E8%99%9B%E4%B8%BB%E8%A6%81%E6%98%AF%E7%84%A1%E5%8A%9B
附子理中湯	  	來源	
http://yibian.hopto.org/fang/?fno=691
【辨證要點】

腹痛不渴。
或嘔或利。
四肢厥冷。
舌淡苔白。
脈沈遲。

* 刺绣
https://detail.tmall.com/item.htm?spm=a220o.1000855.w4004-15715496505.2.Md9Fx1&abtest=_AB-LR129-PR129&pvid=257c5d55-2361-40e7-afb2-b6a3b3629b0e&pos=1&abbucket=_AB-M129_B17&acm=03130.1003.1.701602&id=37946607843&scm=1007.12929.25829.100200300000000&skuId=3193373981693

蓝牡丹 绿新花
* 网址
http://www.ittun.com/

