#+OPTIONS: \n:t
#+OPTIONS: toc:nil
* hexo博客安装实践

mkdir hexo && cd hexo
sudo cnpm install -g hexo

提示 link /usr/local/node/bin/hexo@ -> /usr/local/node/lib/node_modules/hexo/bin/hexo
-g代表全局依赖 安装后可以在其他目录任意调用，如webback等可以使用全局安装;
本地安装的优点是升级依赖、重命名等时可以和全局的依赖避免冲突 
参考 http://www.cnblogs.com/zhuzhenwei918/p/7228915.html

sudo hexo init
sudo cnpm install hexo-deployer-git --save
hexo d

使用命令
#+BEGIN_EXAMPLE
hexo generate = hexo g
hexo server = hexo s
hexo delopy = hexo d
hexo new = hexo n
#+END_EXAMPLE
参考 [[http://www.jianshu.com/p/ed32ac187dbc]]
更多参考 [[https://xuanwo.org/2015/03/26/hexo-intor/]]

* 树型结构数据呈现
*** 可分页版 
从数组看依次取出10条id,在根据id取出相应的父节点数据，最后过滤10条里的重复数组
#+ATTR_HTML: :textarea t :height 200
#+BEGIN_SRC php
private function createTree($array, $pid = 0)
{
    $ret = array();

    foreach($array as $key => $value){
        if($value['pid'] == $pid){
            $tmp = $value;
            unset($array[$key]);
            $tmp['list'] = $this->createTree($array, $value['id']);
            $ret[] = $tmp;
        }
    }

    return $ret;
}

private function array_multiToSingle($array,$clearRepeated=false)
{
    if(!isset($array)||!is_array($array)||empty($array)){
        return false;
    }
    if(!in_array($clearRepeated,array('true','false',''))){
        return false;
    }
    static $result_array=array();
    foreach($array as $value){
        if(is_array($value)){
            $this->array_multiToSingle($value);
        }else{
            $result_array[]=$value;
        }
    }
    if($clearRepeated){
        $result_array=array_unique($result_array);
    }
    return $result_array;
}


private function array_SingleTo2($array)
{
    static $result_array=array();
    $len = count($array)/10;
    for($i=0;$i<$len;$i++){
        $result_array[$i]['level'] = array_shift($array);
        $result_array[$i]['id'] = array_shift($array);
        $result_array[$i]['pid'] =array_shift($array);
        $result_array[$i]['name'] = array_shift($array);
        $result_array[$i]['user'] = array_shift($array);
        $result_array[$i]['auth'] = array_shift($array);
        $result_array[$i]['updated'] = array_shift($array);
        $result_array[$i]['title'] = array_shift($array);
        $result_array[$i]['user_id'] = array_shift($array);
        $result_array[$i]['comments_id'] = array_shift($array);
    }

    return $result_array;
}

private function array_addLevel($arr)
{

    foreach($arr as $key=>$val){

        array_unshift($arr[$key],0);

        if(isset($val['list']) && is_array($val['list']) && !empty($val['list'])){
            foreach($val['list'] as $k=>$v){
                array_unshift($arr[$key]['list'][$k],1);

                //
                if(isset($v['list']) && is_array($v['list']) && !empty($v['list'])){
                    foreach($v['list'] as $kk=>$vv){
                        array_unshift($arr[$key]['list'][$k]['list'][$kk],2);
                    }
                }
                //
            }
        }

    }

    return $arr;
}

function array_unique_2d($array2D){
    $temp = $res = array();
    foreach ($array2D as $v){
        $v = json_encode($v);  //降维,将一维数组转换字符串
        $temp[] = $v;
    }
    $temp = array_unique($temp);    //去掉重复的字符串,也就是重复的一维数组
    foreach ($temp as $item){
        $res[] = json_decode($item,true);   //再将拆开的数组重新组装
    }
    return $res;
}

/**
 * 管理端AJAX数组
 * @param Request $request
 * @param String 'comments_resource'
 * @return mixed
 */
public function listResourceIndex(Request $request)
{
    $draw = $request->input('draw', 1);
    $start = $request->input('start', 0);
    $length = $request->input('length', 10);
    $auth = intval($request->input('auth', 0));
    $order['name'] = $request->input('columns.' . $request->input('order.0.column').'.name');
    $order['dir'] = $request->input('order.0.dir', 'asc');
    $search['value'] = $request->input('search.value', '');
    $search['regex'] = $request->input('search.regex', false);

	//$model = DB::table('comments_resource as cr');
	//
	//if ($search['value']) {
	//    if ($search['regex'] == 'true') {//传过来的是字符串不能用bool值比较
	//        $model = $model->where('title', 'like', "%{$search['value']}%");
	//    } else {
	//        $model = $model->where('title', $search['value'])->orWhere('title', $search['value']);
	//    }
	//}
	//$model = $model->leftJoin('comments as c', 'c.comments_id', '=', 'cr.comments_id');
	//$model = $model->leftJoin('users as u', 'u.id', '=', 'cr.user_id');
	//$count = $model->count();
	//
	//
	//$model = $model->orderBy('cr.updated_at', $order['dir']);
	//$arr = $model->offset($start)->limit($length)->get([
	//    'level','comments_resource_id as id','parent_id as pid','txt as name','u.name as user',
	//    'is_check as auth','cr.updated_at as updated','title','cr.user_id','cr.comments_id']);
	//$auth = Comments::COMMENTS_CHECK_ING;
    
    if($auth == '0'){

        $arr0 = DB::select('
                    SELECT comments_resource_id as id
                    FROM comments_resource t2
                    LEFT JOIN comments as c ON c.comments_id = t2.comments_id 
                    LEFT JOIN users as u ON u.id = t2.user_id
                    WHERE t2.is_check = '.$auth.'
                    ORDER BY t2.comments_resource_id
                ');

        $arr1 = DB::select('
                    SELECT comments_resource_id as id
                    FROM comments_resource t2
                    LEFT JOIN comments as c ON c.comments_id = t2.comments_id 
                    LEFT JOIN users as u ON u.id = t2.user_id
                    WHERE t2.is_check = '.$auth.'
                    ORDER BY t2.comments_resource_id
                    LIMIT 10 OFFSET 0;
                ');
        
        $arr2 = [];
        foreach($arr1 as $val){
            $arr2[]= DB::select('
                SELECT level,comments_resource_id as id,parent_id as pid,txt as name,u.name as user,
                    is_check as auth,t2.updated_at as updated,title,t2.user_id,t2.comments_id
                FROM ( 
                    SELECT 
                            @r AS _id, 
                            (SELECT @r := parent_id as pid FROM comments_resource WHERE comments_resource_id = _id) AS pid, 
                             @l := @l + 1 AS lvl 
                    FROM 
                            (SELECT @r := '.$val->id.', @l := 0) vars, 
                            comments_resource h 
                    WHERE @r <> 0) t1 
                JOIN comments_resource t2 ON t1._id = t2.comments_resource_id
                LEFT JOIN comments as c ON c.comments_id = t2.comments_id 
                LEFT JOIN users as u ON u.id = t2.user_id 
                ORDER BY t2.comments_resource_id
            ');
            
        }

        $arr3 = [];
        foreach($arr2 as $val){
            foreach($val as $v){
                array_push($arr3, $v);
            }
        }

        $arr = $this->array_unique_2d($arr3);

        $count = count($arr0);

    }else{

        $arr12 = DB::select('
                SELECT comments_resource_id as id
                FROM comments_resource t2
                LEFT JOIN comments as c ON c.comments_id = t2.comments_id 
                LEFT JOIN users as u ON u.id = t2.user_id 
                WHERE t2.is_check = '.$auth.';
            ');

        $arr11 = DB::select('
                SELECT level,comments_resource_id as id,parent_id as pid,txt as name,u.name as user,
                    t2.is_check as auth,t2.updated_at as updated,title,t2.user_id,t2.comments_id
                FROM comments_resource t2
                LEFT JOIN comments as c ON c.comments_id = t2.comments_id 
                LEFT JOIN users as u ON u.id = t2.user_id 
                WHERE t2.is_check = '.$auth.'
                ORDER BY t2.comments_resource_id
                LIMIT '.$length.' OFFSET '.$start.';
            ');
        $arr = json_decode(json_encode($arr11), true);

        $count = count($arr12);
    }
    
    
	//$arr = json_decode(json_encode($arr1), true);
	//$arr = $this->createTree($arr);
	//$arr = $this->array_multiToSingle($arr);
	//$arr = $this->array_SingleTo2($arr);

    return [
        'draw' => $draw,
        'recordsTotal' => $count,
        'recordsFiltered' => $count,
        'data' => $arr
    ];
}
#+END_SRC
参考 [[http://www.dewen.net.cn/q/1511/%E5%A6%82%E4%BD%95%E5%AF%B9php+%E5%81%9A%E4%BA%8C%E7%BB%B4%E6%95%B0%E7%BB%84%E7%9A%84array_unique][php函数二维数组惟一过滤]]
*** 不可分页版
控制器二维变嵌套，再变一维，再变二维返回前端
#+BEGIN_SRC php 
function createTree($array, $pid = 0)
{
    $ret = array();

    foreach($array as $key => $value){
        if($value['pid'] == $pid){
            $tmp = $value;
            unset($array[$key]);
            $tmp['list'] = $this->createTree($array, $value['id']);
            $ret[] = $tmp;

        }
    }

    return $ret;
}


function array_multiToSingle($array,$clearRepeated=false)
{
    if(!isset($array)||!is_array($array)||empty($array)){
        return false;
    }
    if(!in_array($clearRepeated,array('true','false',''))){
        return false;
    }
    static $result_array=array();
    foreach($array as $value){
        if(is_array($value)){
            $this->array_multiToSingle($value);
        }else{
            $result_array[]=$value;
        }
    }
    if($clearRepeated){
        $result_array=array_unique($result_array);
    }
    return $result_array;
}

function array_SingleTo2($array){
    static $result_array=array();
    $len = (count($array)+1)/3-1;
    for($i=0;$i<$len;$i++){
        $result_array[$i]['id'] = array_shift($array);
        array_shift($array);
        $result_array[$i]['name'] = array_shift($array);
    }

    return $result_array;
}

public function index()
{
    $arr = array(
        array('id'=>1,'pid'=>0,'name'=>'1'),
        array('id'=>2,'pid'=>1,'name'=>'1-1'),
        array('id'=>3,'pid'=>0,'name'=>'2'),
        array('id'=>4,'pid'=>3,'name'=>'3-3'),
        array('id'=>5,'pid'=>3,'name'=>'3-4'),
        array('id'=>6,'pid'=>1,'name'=>'1-2')
    );

    $arr = $this->createTree($arr);
    $arr = $this->array_multiToSingle($arr);
    $arr = $this->array_SingleTo2($arr);
    dd($arr);die;

    $tree = json_encode($this->createTree($arr), JSON_UNESCAPED_UNICODE);

    return view('admin.comments.index',['tree'=>$tree]);
}
#+END_SRC
*** 参考版 json树形数组->html

var menulist = {
    "menulist": [
        { "MID": "M001", "MName": "首页", "Url": "#", "menulist": "" },
        { "MID": "M002", "MName": "车辆买卖", "Url": "#", "menulist":
            [
                { "MID": "M003", "MName": "新车", "Url": "#", "menulist":
                    [
                        { "MID": "M006", "MName": "奥迪", "Url": "#", "menulist": "" },
                        { "MID": "M007", "MName": "别克", "Url": "#", "menulist": "" }
                    ]
                },
                { "MID": "M004", "MName": "二手车", "Url": "#", "menulist": "" },
                { "MID": "M005", "MName": "改装车", "Url": "#", "menulist": "" }
            ]
        },
        { "MID": "M006", "MName": "宠物", "Url": "#", "menulist": "" }
    ]
};

$("#click").click(function () {
     var showlist = $("<ul></ul>");
     showall(menulist.menulist, showlist);
     $("#tree").append(showlist);
});


//menu_list为json数据
//parent为要组合成html的容器
function showall(menu_list, parent) {
    for (var menu in menu_list) {
        //如果有子节点，则遍历该子节点
        if (menu_list[menu].menulist.length > 0) {
            //创建一个子节点li
            var li = $("<li></li>");
            //将li的文本设置好，并马上添加一个空白的ul子节点，并且将这个li添加到父亲节点中
            $(li).append(menu_list[menu].MName).append("<ul></ul>").appendTo(parent);
            //将空白的ul作为下一个递归遍历的父亲节点传入
            showall(menu_list[menu].menulist, $(li).children().eq(0));
        }
        //如果该节点没有子节点，则直接将该节点li以及文本创建好直接添加到父亲节点中
        else {
            $("<li></li>").append(menu_list[menu].MName).appendTo(parent);
        }
    }
 }

参考 http://www.cnblogs.com/hxhbluestar/archive/2011/11/17/2252009.html
*** 优化版：php二维数组处理返回嵌套数组，前端循环变量显示
#+BEGIN_SRC php

function createTree($array, $pid = 0){
    $ret = array();

    foreach($array as $key => $value){
        if($value['pid'] == $pid){
            $tmp = $value;
            unset($array[$key]);
            $tmp['list'] = $this->createTree($array, $value['id']);
            $ret[] = $tmp;
        }
    }

    return $ret;
}

public function index()
{
    $array = array(
        array('id'=>1,'pid'=>'0','name'=>'11111'),
        array('id'=>2,'pid'=>'1','name'=>'22222'),
        array('id'=>3,'pid'=>'0','name'=>'33333'),
        array('id'=>4,'pid'=>'3','name'=>'44444'),
        array('id'=>5,'pid'=>'4','name'=>'55555'),
        array('id'=>6,'pid'=>'1','name'=>'66666')
    );

    $tree = json_encode($this->createTree($array), JSON_UNESCAPED_UNICODE);

    return view('admin.comments.index',['tree'=>$tree]);
}

#+END_SRC
#+BEGIN_SRC js

<button id="click">click</button>
            <div id="tree">

            </div>

var tree = {}
    tree.list = {!! $tree !!}

$("#click").click(function () {
    var showlist = $("<ul></ul>");
    showall(tree.list, showlist);
    $("#tree").append(showlist);
});

function showall(list, parent) {
    for (var index in list) {
        if (list[index].list.length > 0) {
            var li = $("<li></li>");
            $(li).append(list[index].name).append("<ul></ul>").appendTo(parent);
            showall(list[index].list, $(li).children().eq(0));
        }else {
            $("<li></li>").append(list[index].name).appendTo(parent);
        }
    }
}

#+END_SRC
* json php数据格式转化

js
JSON 字符串 -> JavaScript 对象
#+BEGIN_EXAMPLE
JSON.Parse()
#+END_EXAMPLE

JavaScript 对象 -> JSON 字符串	
~JSON.stringify()~	
php
Converting an array/stdClass -> stdClass
$stdClass = json_decode(json_encode($booking));
Converting an array/stdClass -> array
$array = json_decode(json_encode($booking), true);
stdClass -> array  一维
$array = (array)$stdClass;

* jquery
plugins  https://plugins.jquery.com/
pace.min.js   页面加载提示进度条
jquery-1.9.1.min.js   1.9是最后支持ie678的版本
jquery-migrate-1.1.0.min.js   提供到此版本的api缺失
jquery.slimscroll.min.js   在固定区域里显示文本，超出添加滑块
jquery.cookie.js    cookie
jquery.gritter.js    session消息提示
jquery.dataTables.js  
dataTables.bootstrap.min.js    datatables
sweetalert.js   警告框（删除时等）

** each
var arrSource=[]

    // 授权
    $(document).on('click','.auth',function(){  
     $(this).parents('tr').children('td').each(function (i) {

            arrSource[i] = []
            if(i==0){
                console.log(arrSource[i].push($(this).children(0).val()))
            }else{

                arrSource[i].push($(this).html())
            }
        });
    })
** class的选择点击事件
$(document).on('click', '.spanTagDel', function(){
            var tagName = $(this).parent().text()
            alert(tagName)
        })
** jquery手册提示
选择标签找关键字  筛选 >过滤 查找 
* scrollTop

https://stackoverflow.com/questions/16475198/jquery-scrolltop-animation

$("html, body").animate({ scrollTop: 50 }, 300);

* datatable

Debug
刷新不出页面 
1检查和html列和datatable js的列对应关系 
2 如果以上对应关系正确，清除缓存

DOM / jQuery events 获取一行的数据
DataTables events  点击搜索，分页等事件
Column rendering 可以渲染链接的列，自定义列，按钮等
Setting defaults 设置所有datatable的相同的共同的一些参数
Row created callback 对每一列的数据处理显示 比如判断大小
Footer callback 计算每页价格的总计
Custom toolbar elements 定义div button标签到datatable里
Generated content for a column  列中显示按钮，获取数据
Custom data source property  ajax获取的数据是对象格式，对象有属性比如{"data":[[...],[...]]}
Deferred rendering for speed  延迟加载，datatable只渲染当前页面的数据，提高速度

Row selection (multiple rows) 获取所选数据

Select
单选，全选等按钮 已选择状态 Buttons 
重新加载时可以维护已选择的不消失 Retain selection on reload
点击按钮获取datatable数据 Get selected items

例子

** 结合daterangepicker实现Datatables表格带参数查询
 http://datatables.club/example/user_share/send_extra_param.html
** 操作按钮用js表现，checkbox第一列
                    "columnDefs": [
                    {
                        "render": function ( data, type, row ) {
                            return ' <a href="{{ $_SERVER['HTTP_HOST'] }}/admin/catalog/'+row.id+'/edit">' +
                                '<button id="'+row.id+'" class="btn btn-xs btn-success">' +
                                '<i class="fa fa-pencil"></i> 编辑 </button></a> ' +
                                ' <button id="'+row.id+'" class="btn btn-xs btn-danger">' +
                                '<i class="fa fa-trash"></i> 删除 </button> ';
                        },
                        "targets": 4
                    },
                    {
                        render: function ( data, type, row ) {
                            return '';
                        },
                        orderable: false,
                        className: 'select-checkbox cursor-pointer',
                        targets:   0
                    }
]
** 修改datatable 的默认英文如Previous为中文
google 搜索datatables文档
文档中找language 的菜单
http://l-lin.github.io/angular-datatables/archives/#!/api
ctrl+F 搜索lang
然后到文档中修改
** datatables + vue 实现增加删除列表功能
#+BEGIN_SRC js
<div class="form-group">
  <label class="control-label col-md-2 col-sm-2" for="url">资源选择 * :</label>
  <div class="col-md-4 col-sm-4">
    <table class="table table-bordered table-hover" id="datatable">
      <thead>
        <tr>
          <th style="width: 10px;"></th>
          <th>资源列表</th>
          <th style="width:20px;"></th>
        </tr>
      </thead>
    </table>
  </div>
  <div class="col-md-4 col-sm-4">
    {{--<div class="input-group">--}}
    {{--<input type="hidden" name="resource_id" value="" />--}}
    {{--<input class="form-control" type="text" name="resource_name" placeholder="已选资源展示" />--}}
    {{--<div class="input-group-btn">--}}
    {{--<button type="button" class="btn btn-success">选择资源</button>--}}
    {{--</div>--}}
    {{--</div>--}}
    <div class="height-50"></div>
    {{--<div id="textareaShow" class="form-control" style="height:60px;margin-bottom:5px;">
    <div id="app">
    <button v-on:click="add">add</button>
    <button v-on:click="del(22)">del</button>
    <div v-for="(item, index) in items" style="height:25px;">
    <span v-bind:id="item.id" class="bg-info btn-xs"> ${ item.name } 
    <i style="cursor:pointer"> &times;</i>
    </span>
    ${ index } - ${ item.id } - ${ item.name }
    </div>
    </div>
    </div>--}}
    <div id="inner-content-div">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            {{--<th style="width: 10px;"></th>--}}
            <th>已选资源</th>
            <th style="width:50px;"></th>
          </tr>
        </thead>
        <tbody id="app">
          <tr  v-for="(item, index) in items">
            <td>${ item.name }</td>
            <td><a v-bind:id="item.id" v-on:click="del(item.id)" class="btn btn-xs">
              <i class="fa fa-trash"></i></a></td>
          </tr>
        </tbody>
      </table>
    </div>


  </div>

</div>

<script>
 var table = $('#datatable').DataTable({
	 "processing": true,
	 'language': {
		 "url": "{!! asset('asset_admin/assets/lang/datatable.zh_cn.lang') !!}"
	 },
	 "serverSide": true,
	 'searchDelay': 300,//搜索延时
	 'search': {
		 regex: true//是否开启模糊搜索
	 },
	 "dom": 'frtpB',
	 'order': [[1, 'desc']],
	 'select': {
		 style: 'multi',
		 selector: 'td:first-child',
		 info: false
	 },
	 buttons: [
		 {
			 text: '批量添加',
			 action: function () {
				 var count = table.rows( { selected: true } ).count();
				 // $('#textareaShow').val(count)
				 var data = table.rows( { selected: true } ).data().toArray();
				 var str = '', selected = [], target = []
				 for(var i=0;i<count;i++){
                     selected[i] = {id:data[i].id, name:filterHTML(data[i].name)}
				 }

				 for(var j=0;j<selected.length;j++){
                     app.add(selected[j])
				 }

				 // for(var i=0;i<count;i++){
				 //     console.log(data[i].id)
				 //     str += ' <span data-id="'+data[i].id+'" class="bg-info btn btn-xs">'+filterHTML(data[i].name)
				 //         +'<i> &times;</i></span> '
				 // }
				 // $('#textareaShow').append(str)
			 }
		 }
	 ],
	 "columnDefs": [
		 {
			 render: function (data, type, row) {
				 return '';
			 },
			 orderable: false,
			 className: 'select-checkbox cursor-pointer',
			 targets: 0
		 },
		 {
			 render: function (data, type, row) {
				 return '<a data-id="'+data+'"  data-name="'+filterHTML(row.name)+'" class="btnAdd btn btn-xs"><i class="fa fa-plus"></i></a>';
			 },
			 orderable: false,
			 targets: 2
		 }
	 ],
	 "ajax": {
		 'url': "/admin/catalog/ajaxIndex",
		 'data': {
			 'parent': function () {
				 return $('input[name="parent"]').val();
			 }
		 }
	 },
	 "columns": [
		 {"data": "id", "name": "id", "orderable": false},
		 {"data": "name", "name": "name", "orderable": false},
		 {"data": "id", "name": "id", "orderable": false},
	 ]
 });//end table



 var app = new Vue({
	 delimiters: ['${', '}'],
	 el: '#app',
	 data: {
		 items: [
			 { id: 11, name: 'aaaa' },
			 { id: 22, name: 'bbbb' },
			 { id: 33, name: 'cccc' },
		 ]
	 },
	 methods: {
		 add: function (obj) {
			 // var str = ''
			 // for(var i=0;i<this.items.length;i++){
			 //     str += this.items[i].id+'--'+this.items[i].name
			 // }
			 // console.log(str)
			 var bool=true;
			 this.items.forEach(function(element) {
				 if(element.id==obj.id){
					 $.gritter.add({
						 title: '操作消息！',
						 text: element.name+' 已经添加了，请重新操作！'
					 });
					 console.log(element.name+' 重复了')
					 bool = false
				 }
			 });

			 if(bool){
				 this.items.push(obj)
			 }

			 table.rows().deselect();

		 },
		 del: function(id){

			 var target = []
			 this.items.forEach(function(element) {
				 if(element.id!=id){
					 target.push({id:element.id,name:element.name})
				 }else{
					 console.log('已删除 '+element.name)
				 }
			 });
			 this.items = target
		 }
     }
 })//end app


 //添加资源
 $('#datatable').on('click','.btnAdd',function(){
     var id = $(this).attr('data-id')
     var name = $(this).attr('data-name')
     app.add({id:id,name:name})
 })

 //固定选择区域
 $('#inner-content-div').slimScroll({
     height: '400px',
     railVisible: true,
	 //alwaysVisible: true
 }); 
</script>
#+END_SRC
* js location
location.reload()

* js添加删除class
#+BEGIN_SRC js
var classVal = document.getElementById("id").getAttribute("class");

//删除的话
classVal = classVal.replace("someClassName","");
document.getElementById("id").setAttribute("class",classVal );

//添加的话
classVal = classVal.concat(" someClassName");
document.getElementById("id").setAttribute("class",classVal );

//替换的话
classVal = classVal.replace("someClassName","otherClassName");
document.getElementById("id").setAttribute("class",classVal );
#+END_SRC
* bower 
bower install jstree --save 总是报错
使用bower install jstree 在bower_components生成jstree目录
在次bower install jstree --save 在bower.js添加jstree项

* checkbox
** jquery

$("input[type='checkbox']").prop("checked");  //选中复选框为true，没选中为false
$("input[type='checkbox']").prop("disabled", false);
$("input[type='checkbox']").prop("checked", true);


    $(function(){
        $('#sourceAll').click(function(ev){
            $('INPUT[name="chk"]').attr('checked',$('#sourceAll').prop('checked'));  //attr可以改为prop试试
        });

        $('INPUT[name="chk"]').click(function(ev){
            $('#sourceAll').attr('checked',
                $('INPUT[name="chk"]:checked').length == $('INPUT[name="chk"]').length);
        });
    });

	$('input[name="chkUsers"]:checked').each(function () {
            id_array.push($(this).val());
    });

** js
    全选
    $("#sourceAll").click(function() {
        if (this.checked) {
            allCheck('chk',true);
        } else {
            allCheck('chk',false);
        }
    })

    function allCheck(name,boolValue) {
        var allvalue = document.getElementsByName(name);
        for (var i = 0; i < allvalue.length; i++) {
            if (allvalue[i].type == "checkbox")
                allvalue[i].checked = boolValue;
        }
    }


       var checkbox=document.getElementsByName('chkUsers');
        for(var i=0;i<checkbox.length;i++){
            if(checkbox[i].checked==true){
                id_array.push(checkbox[i].value);
            }
        }
* cookie
//http://www.cnblogs.com/Darren_code/archive/2011/11/24/Cookie.html

    function getCookie(c_name){
        if (document.cookie.length>0){
            c_start=document.cookie.indexOf(c_name + "=")
            if (c_start!=-1){
                c_start=c_start + c_name.length+1
                c_end=document.cookie.indexOf(";",c_start)
                if (c_end==-1) c_end=document.cookie.length
                return unescape(document.cookie.substring(c_start,c_end))
            }
        }
        return ""
    }

    function setCookie(c_name, value, expiredays){
　　　　var exdate=new Date();
// 　　　　exdate.setDate(exdate.getDate() + expiredays);
        exdate.setHours(exdate.getHours() + expiredays);
　　　　document.cookie=c_name+ "=" + escape(value) + ((expiredays==null) ? "" : ";expires="+exdate.toGMTString());
　　}
* color-admin
** 多个表格，不能绘制显示
desc 能ajax返回数据，但是不能在页面显示出来，提示处理中...
answ 删掉页面的data-sort-id，导致的冲突解决
** div js click on 等事件失效
@section('admin-content')
    <div id="content" class="content">
        <!-- begin breadcrumb -->
        <ol class="breadcrumb pull-right">
            <li><a href="javascript:;">主页</a></li>
            <li><a href="javascript:;">资源管理</a></li>
            <li class="active">新增资源</li>
        </ol>
        <!-- end breadcrumb -->
        <!-- begin page-header -->
        <h1 class="page-header">新增资源 <small></small></h1>
        <!-- end page-header -->

        <!-- begin row -->
        <div class="row">
            {{--<!-- begin col-6 加上这层div js click on 等事件失效 -->--}}
            {{--<div class="col-md-12">--}}
** $('.selectpicker').selectpicker('render');加上后好像与$.ajax方法冲突

* Composer 安装与使用
  参考 https://pkg.phpcomposer.com/
  https://laravel-china.org/topics/1901/correct-method-for-installing-composer-expansion-pack

** composer 安装
php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');"

php composer-setup.php

php -r "unlink('composer-setup.php');"

全局安装
sudo mv composer.phar /usr/local/bin/composer

经常执行 composer selfupdate 以保持 Composer 一直是最新版本

镜像用法
修改当前项目的 composer.json 配置文件
进入你的项目的根目录（也就是 composer.json 文件所在目录），执行如下命令：

composer config repo.packagist composer https://packagist.phpcomposer.com
上述命令将会在当前项目中的 composer.json 文件的末尾自动添加镜像的配置信息（你也可以自己手工添加）：

"repositories": {
    "packagist": {
        "type": "composer",
        "url": "https://packagist.phpcomposer.com"
    }
}


** 正确的 Composer 扩展包安装方法
流程一：新项目流程#

创建 composer.json，并添加依赖到的扩展包；
运行 composer install，安装扩展包并生成 composer.lock；
提交 composer.lock 到代码版本控制器中，如：git;

流程二：项目协作者安装现有项目#

克隆项目后，根目录下直接运行 composer install 从 composer.lock 中安装 指定版本 的扩展包以及其依赖；
此流程适用于生产环境代码的部署。

流程三：为项目添加新扩展包#

使用 composer require vendor/package 添加扩展包；
提交更新后的 composer.json 和 composer.lock 到代码版本控制器中，如：git;


composer install - 如有 composer.lock 文件，直接安装，否则从 composer.json 安装最新扩展包和依赖；
composer update - 从 composer.json 安装最新扩展包和依赖；
composer update vendor/package - 从 composer.json 或者对应包的配置，并更新到最新；
composer require new/package - 添加安装 new/package, 可以指定版本，如： composer require new/package ~2.5.
* laravel
                                    
** 调试
bug 新建插入字段不成功
  fix 检查Model 的fill

报错
  FatalThrowableError in 2154f392745gf102547be138a945a11b58e5649203.php line 2: Call to undefined method Illuminate\View\Factory::getFirstLoop()
php artisan view:clear

route问题访问不到
  $router->get('adminuser/changeSelf',...必须在$router->resource('adminuser', 'AdminUserController');前面
** laravel-my
composer create-project laravel/laravel laravel-my --prefer-dist
# 注：有dist和source两种安装方式，dist是强制使用压缩包，而source是使用源代码安装，如果是想从source安装，那么可以改成--prefer--source
composer require "maatwebsite/excel": "~2.1.0"
** 单个项目ajax删除实现
           $.ajaxSetup({
                headers:{
                    'X-CSRF-TOKEN':'{!! csrf_token() !!}'
                }
            })
                        $.ajax({
                            url:'/admin/catalog/'+data.id,
                            type:'POST',
                            data:'_method=DELETE',
                            success:function(data){
                                console.log(data)
                                $.gritter.add({
                                    title: '操作消息！',
                                    text: '删除成功'
                                });
                                location.reload()  //刷新时弹出消息来不及显示，需要通过php端来实现跳转才好
                            },
                            error:function(xhr){
                                console.log('error')
                                console.log(xhr)
                            }
                        })//end ajax
** 开启项目流程
编写.env
composer dump-autoload
php artisan key:genarate

** url带参数
<a href="{{ URL::to('admin/source/iauth').'?'.http_build_query(['id'=>$data->source_id, 'title'=>$data->title, 'update'=>$data->updated_at]) }}"  data-id="{{ $data->source_id }}" data-title="{{ $data->title }}" data-update="{{ $data->updated_at }}" class="btn btn-inverse m-r-5 m-b-5">资源授权</a>

** 任务调度
   sudo vim /etc/crontab
  * * * * root /data/wwwroot/www.hui.c/artisan schedule:run >> /dev/null 2>&1

/etc/init.d/crond start
** 时间 created_at updated_at

http://www.cnblogs.com/Eden-cola/p/laravel-created-at-column-name.html
http://www.piaoyi.org/php/Laravel-created_at-updated_at-timestamp.html
* laravel ajax上传文件
** 直接上传到服务器交互
         $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $("input[name='_token']").val()
            }
        });

        $('#pic').on('click', function(){

            $('#photo_upload').trigger('click');

            $('#photo_upload').on('change', function(){
                var obj = this;
                var formData = new FormData();
                formData.append('thumb', this.files[0]);

                $.ajax({
                    url: '/admin/source/uploadPic/',
                    type: 'post',
                    data: formData,
                    processData: false,
                    contentType: false,
                    beforeSend:function(){
                        $('#pic').attr('src', '/img/uploading.png');
                    },
                    success: function(data){
                        if(data['ServerNo']=='200'){
                            $('#pic').attr('src', '/uploads/'+data['ResultData']);
                            $('#thumb').val(data['ResultData']);
                            $(obj).off('change');
                        }else{
                            alert(data['ResultData']);
                        }
                    },
                    error: function(XMLHttpRequest, textStatus, errorThrown) {
                        $('#pic').attr('src', '/img/error.png');
                        var number = XMLHttpRequest.status;
                        alert("错误号"+number+"文件上传失败!");
                    },
                    async: true
                });
            });
        });

注:url项/admin/source/uploadPic/ 前面和后面的/可以去掉测试有不同的效果，比如form里action有/source/144 的情况，file按钮在form里时

/**
     * 检查文件
     *
     * @param $file
     * @return array
     */
    private function checkFile($file)
    {
        if ($file->getClientSize() > $file->getMaxFilesize()) {
            return ['status' => false, 'msg' => '文件大小不能大于2M'];
        }

        if (!$file->isValid()) {
            return ['status' => false, 'msg' => '上传文件不符合要求'];
        }

        return ['status' => true];
    }

    /**
     * 文件上传
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function uploadPic(Request $request)
    {
        $file = $request->file('thumb');

        $check = $this->checkFile($file);

        if(!$check['status']){
            return response()->json(['ServerNo' => '400','ResultData' => $check['msg']]);
        }

        $path = public_path('uploads');
        $postfix = $file->getClientOriginalExtension();
        $fileName = md5(time().rand(0,10000)).'.'.$postfix;

        if(!$file->move($path,$fileName)){
            return response()->json(['ServerNo' => '400','ResultData' => '文件保存失败']);
        }else{
            return response()->json(['ServerNo' => '200','ResultData' => $fileName]);
        }

    }

** 只有前端交互，可预览
#+BEGIN_SRC js
                            <div class="form-group" id="areaPic">
                                <label class="control-label col-md-2 col-sm-2" for="thumb">资源缩略图 </label>
                                <div class="col-md-8 col-sm-8">
                                    <img src="/uploads/{{ $data['thumb']? $data['thumb']:'noimage.gif'
                                    }}" id="pic" style="cursor: pointer;height:100px"/>
                                    <p class="help-block">点击图片上传(格式：png/jpg/jpeg/gif, 不大于2M)</p>
                                    <input type="file" id="fileUpload" style="display: none;" />
                                    <input type="hidden" id="inputUpload" name="thumb" value="{{ $data['thumb'] }}" />
                                </div>
                            </div>


        //上传图片
        $('#pic').on('click', function(){
            $('#fileUpload').trigger('click');
        });

        $('#fileUpload').on('change', function(event){

            $('#inputUpload').removeAttr('name')
            $('#fileUpload').attr('name','thumb')

            if(fileUploadSize(event.target) > 1024*1024*2){
                $.gritter.add({
                    title: '操作消息！',
                    text: '文件超出大小限制'
                });
                return;
            }

            var src = event.target || window.event.srcElement; //获取事件源，兼容chrome/IE
            var filename = src.value;
            var postfix = filename.substring( filename.lastIndexOf('.')+1 );

            if(['png','jpeg','jpg','gif'].indexOf(postfix) == '-1'){
                $.gritter.add({
                    title: '操作消息！',
                    text: '文件格式不符合'
                });
                return;
            }

            var $file = $(this);
            var fileObj = $file[0];
            var windowURL = window.URL || window.webkitURL;
            var dataURL;

            if(fileObj && fileObj.files && fileObj.files[0]){
                dataURL = windowURL.createObjectURL(fileObj.files[0]);
                $("#pic").attr('src',dataURL);
            }else{
                dataURL = $file.val();
                var imgObj = document.getElementById("pic");
                imgObj.style.filter = "progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale)";
                imgObj.filters.item("DXImageTransform.Microsoft.AlphaImageLoader").src = dataURL;
            }
        })
        //end 上传图片

#+END_SRC
#+BEGIN_SRC php
    /**
     * 文件上传
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function uploadFile(Request $request)
    {
        if($thumb = $request->input('thumb')){
            return ['code' => 2000,'img' => $thumb, 'error'=>'没有修改文件'];
        }

        if($file = $request->file('thumb')){
            $path = public_path('uploads');
            $postfix = $file->getClientOriginalExtension();
            $fileName = md5(time().rand(0,10000)).'.'.$postfix;

            if(!in_array($postfix, array('png','jpeg','jpg','gif'))){
                return ['code' => 2001,'img' => $fileName, 'error'=>'文件格式不对'];
            }

            if($file->getSize() > 1024*1024*2){
                return ['code' => 2002,'img' => $fileName, 'error'=>'文件太大'];
            }

            if($file->move($path, $fileName)){
                return ['code' => 2000,'img' => $fileName, 'error'=>''];
            }else{
                return ['code' => 5000,'img' => $fileName, 'error'=>'文件上传失败'];
            }
        }else{
            return ['code' => 2000,'img' => '', 'error'=>'无上传文件'];
        }

    }

    /**
     * 新建数据
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {

        $params = $request->except('jsonStrTags');
        $params['tags'] = json_decode($request->input('jsonStrTags'),true);

        $arr = $this->uploadFile($request);
        if($arr['code'] !== 2000){
            flash($arr['error'],'error');
            return back();
        }else{
            $params['thumb'] = $arr['img'];
        }

        $res = $this->catalog->insertCatalog($params);

        if($res){
            flash('保存成功','success');
            $pid = intval($request->input('parent_id',0));
            return redirect('admin/catalogs'.($pid>0?'/'.$pid:''));
        }else{
            $code = $this->catalog->getMessageErrorCode();
            if(isset($code)){
                if(is_string($code) && $code>2000 && $code<2100){
                    flash($this->catalog->getMessageError(),'error');
                }elseif($code=='-1005'){
                    flash('分类名称重名','error');
                }
            }
            return back()->withInput();
        }
    }

#+END_SRC
* laravel angular adminlte
管理 php artisan serve
  查看命令选项 php artisan help make:model
              php artisan make:model source
source_id  和sourceId 的注意事项
source-list.component.js 的data.source_id
config/route.config.js  
source-edit.component.js

* 安装 ubuntu apache2 nginx php7 ThinkPHP Laravel
** apache2
参考 https://www.howtoing.com/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-16-04/
    https://www.howtoing.com/how-to-set-up-apache-virtual-hosts-on-ubuntu-16-04/

sudo apt-get update
sudo apt-get install apache2

sudo apache2ctl configtest

sudo vim /etc/apache2/apache2.conf
  ServerName localhost

sudo apache2ctl configtest

开启防火墙
sudo ufw app list

sudo ufw allow in "Apache Full"

测试 http://locahost
管理方法 sudo apache2ctl restart/stop/reload
** nginx 
error: 重启后进入localhost/phpmyadmin 出现nginx forbidden
vim /etc/nginx/sites-enabled/default
把80改为8000
修改 index index.nginx-debian.html;
管理方法 启动 sudo nginx
sudo nginx -s reload/reopen

** 安装PHP

sudo apt-get install php libapache2-mod-php php-mcrypt

sudo vim /etc/apache2/mods-enabled/dir.conf
   DirectoryIndex index.php 移到前面

sudo systemctl restart apache2

sudo systemctl status apache2

sudo vim /var/www/html/phpinfo.php

测试 http://localhost/phpinfo.php

下载项目
sudo chown -R $USER:$USER /var/www 修改目录为当前用户拥有目录

sudo chmod -R 755 /var/www

git clone 
如果下载 sudo git clone ssh... 报错 not permit..
  sudo rm -rf /root/.ssh   
  sudo cp ~/.ssh -r /root/

配置虚拟主机

sudo cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/sz.rr.conf

sudo vim /etc/apache2/sites-available/sz.rr.conf

<VirtualHost *:80>
    ServerAdmin 201313488@qq.com
    ServerName sz.rr
    ServerAlias www.sz.rr
    DocumentRoot /var/www/hourlyrate-admin/php
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

sudo a2ensite sz.rr.conf

# sudo a2dissite 000-default.conf

sudo systemctl restart apache2

sudo vim /etc/hosts
  127.0.0.1   sz.rr

vim /var/www/hourlyrate-admin/php/phpinfo.php
测试 http://sz.rr/phpinfo.php
     http://sz.rr

加入项目目录不同，单独的目录，会出现
error:You don't have permission to access / on this server
参考：https://askubuntu.com/questions/617190/how-to-setup-apache2-virtualhosts-on-your-home-directory-on-ubuntu-14-04
vim /etc/apache2/apache2.conf
copy <Directory /balabala>...</Directory>一份对应的目录

** 调试ThinkPHP
 报错： _STORAGE_WRITE_ERROR_:./Application/Runtime... 
 解决： mkdir ./Application/Runtime
       chmod 777 ./Application/Runtime

 报错： not find function php_curl
 解决： sudo vim /etc/php/7.0/apache2/php.ini
          curl前面去掉;
       sudo apt install php-curl
       sudo systemctl restart apache2
       
 报错：Call to undefined function Think\Template\simplexml_load_string()
 解决： extension=php_xmlrpc.dll
        sudo apt install php7.0-xml
        sudo systemctl restart apache2

** 调试Laravel
安装composer
根目录composer install 
  报错缺ext-mbstring
   解决： sudo vim /etc/php/7.0/apache2/php.ini
          mbstring 前面去掉;
       sudo apt install php-mbstring
  坑：
    vim /var/www/api-backend/public/phpinfo.php
       <?php phpinfo();
    测试 http://pangtu.rr/phpinfo.php ok
    根目录 php -S localhost:8888 -t public/
    测试 http://localhost:8888 ok
    但 http://panggu.rr 报500错
  解决： 
    vim /etc/apache2/sites-available/pangu.rr.conf 
    复制粘贴 /var/www/api-backend/public
    ok
* mysql
** 命令
truncate table 表名;     清除表
** mysql 紧急停止
ubuntu下 /etc/init.d/mysql stop

** 调试
ubuntu 下
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
解决 systemctl start mysql
** 导出
mysqldump -h 192.168.100.159 -u www.data.c -p www.data.c > lbb.sql
                                用户         数据库名
然后输入密码       
** 批量插入测试数据
*** 复制 一个存储过程生成1000万条数据的方法 http://www.bcty365.com/content-35-4815-1.html
-- 创建测试的test表 
DROP TABLE IF EXISTS test;  
CREATE TABLE test(  
    ID INT(10) NOT NULL,  
    `Name` VARCHAR(20) DEFAULT '' NOT NULL,  
    PRIMARY KEY( ID )  
)ENGINE=INNODB DEFAULT CHARSET utf8;  
 
-- 创建生成测试数据的存储过程 
DROP PROCEDURE IF EXISTS pre_test;  
DELIMITER // 
CREATE PROCEDURE pre_test()  
BEGIN  
DECLARE i INT DEFAULT 0;  
SET autocommit = 0;  
WHILE i<10000000 DO  
INSERT INTO test ( ID,`Name` ) VALUES( i, CONCAT( 'Carl', i ) );  
SET i = i+1;  
IF i%2000 = 0 THEN  
COMMIT;  
END IF;  
END WHILE;  
END; // 
DELIMITER ; 
 
-- 执行存储过程生成测试数据 
CALL pre_test();
 
*** 测试
**** 插入30天播放量数据
DROP PROCEDURE IF EXISTS pre_test; 

DELIMITER // 

CREATE PROCEDURE pre_test()  
BEGIN  
DECLARE i INT DEFAULT 1; 
DECLARE totals INT;
DECLARE mydate DATETIME;
SET autocommit = 0;  

WHILE i< 31 DO 

 IF i<10 THEN
 SET mydate = CONCAT( '2017-10-0', i );
 END IF;
 IF i>9 THEN
 SET mydate = CONCAT( '2017-10-', i );
 END IF;
 
INSERT INTO `user_plays_total` (`totals`, `pcs`, `wechats`, `mobiles`, `equipments`, `others`, `created_at`)
 VALUES (ROUND(RAND()*(1500-1300)+1300), ROUND(RAND()*(90-10)+10), ROUND(RAND()*(900-800)+800), '0',
ROUND(RAND()*(500-400)+400), '0', mydate);  

SET i = i+1; 
   
END WHILE;

COMMIT;  
END; // 

DELIMITER ; 
 
-- 执行存储过程生成测试数据 
CALL pre_test();

**** 插入30用户数据,每日增加100个
DROP PROCEDURE IF EXISTS pre_test; 

DELIMITER // 

CREATE PROCEDURE pre_test()  
BEGIN  
DECLARE i INT DEFAULT 1; 
DECLARE totals INT;
DECLARE mydate DATETIME;
SET autocommit = 0;  

WHILE i< 31 DO 

 IF i<10 THEN
 SET mydate = CONCAT( '2017-10-0', i );
 END IF;
 IF i>9 THEN
 SET mydate = CONCAT( '2017-10-', i );
 END IF;
 
INSERT INTO `user_total` (`creaters`, `updaters`,`created_at`)
 VALUES (ROUND(RAND()*(1500-1000)+1000)+100*i, ROUND(RAND()*(5000-4000)+4000)+100*i, mydate);  

SET i = i+1; 
   
END WHILE;

COMMIT;  
END; // 

DELIMITER ; 
 
-- 执行存储过程生成测试数据 
CALL pre_test();

** 统计
https://yq.aliyun.com/ziliao/65088?spm=5176.8246799.blogcont.24.cLUOtc
--查询昨天的信息记录：
--注意 修改原来<= 为=
1 select * from `article` where to_days(now()) – to_days(`add_time`) = 1; 
测试
DB::select('SELECT plays_os,SUM(plays) AS num FROM user_plays 
            WHERE to_days(now()) - to_days(`created_at`) = 1 GROUP BY plays_os');  
** 关于mysql时间类型datetime与timestamp范围

datetime类型取值范围：1000-01-01 00:00:00 到 9999-12-31 23:59:59

timestamp类型取值范围：1970-01-01 00:00:00 到 2037-12-31 23:59:59

timestamp类型具有自动初始化和自动更新的特性。
** 数据库设计书推荐
高性能mysql推荐 Apress.Beginning.Database.Design.2nd.Edition.Jul.2012 是英文版，需要有空的时候读读
另外搜到了 《数据库设计入门经典》中文版书，读了2天，结论是晦涩难懂，实战价值不大
* nginx 
查看配置文件 nginx -t

* docker

阿里云脚本安装
curl -sSL http://acs-public-mirror.oss-cn-hangzhou.aliyuncs.com/docker-engine/internet | sh -
添加APT镜像
检查版本是否改动过 sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list

sudo apt-get update

安装 Docker
sudo apt-get install docker-engine

启动 Docker 引擎
$ sudo systemctl enable docker
$ sudo systemctl start docker

将当前用户加入 docker 组：
$ sudo usermod -aG docker $USER

使用Dockerfile定制镜像
mkdir nginxmy
cd nginxmy
vim Dockfile
FROM nginx
RUN echo '<h1>Hello, Docker!</h1>' > /usr/share/nginx/html/index.html

构建镜像
docker build -t nginx:v3 .

一般来说，应该会将 Dockerfile 置于一个空目录下，或者项目根目录下。
如果该目录下没有所需文件，那么应该把所需文件复制一份过来。如果目录下有些东西确实不希望构建时传给 Docker 引擎，
那么可以用 .gitignore 一样的语法写一个 .dockerignore，该文件是用于剔除不需要作为上下文传递给 Docker 引擎的。

那么为什么会有人误以为 . 是指定 Dockerfile 所在目录呢？这是因为在默认情况下，如果不额外指定 Dockerfile 的话，
会将上下文目录下的名为 Dockerfile 的文件作为 Dockerfile。
这只是默认行为，实际上 Dockerfile 的文件名并不要求必须为 Dockerfile，而且并不要求必须位于上下文目录中
，比如可以用 -f ../Dockerfile.php 参数指定某个文件作为 Dockerfile。
当然，一般大家习惯性的会使用默认的文件名 Dockerfile，以及会将其置于镜像构建上下文目录中。

强制关闭并删除正在运行的程序docker rm -f $(docker ps -q)

* linux
关于递归目录相关命令
cp -R dir/ ./
mv dir ./ # 不用选项
chown -R git:git ./
scp -r project.git/ root@hostname:/opt/git/
* ubuntu
** apt dpkg软件管理
apt-cache search # ------(package 搜索包)
apt-cache show #------(package 获取包的相关信息，如说明、大小、版本等)
apt-get install # ------(package 安装包)
apt-get install # -----(package --reinstall 重新安装包)
apt-get -f install # -----(强制安装, "-f = --fix-missing"当是修复安装吧...)
apt-get remove #-----(package 删除包)
apt-get remove --purge # ------(package 删除包，包括删除配置文件等)
apt-get autoremove --purge # ----(package 删除包及其依赖的软件包+配置文件等（只对6.10有效，强烈推荐）)
apt-get update #------更新源
apt-get upgrade #------更新已安装的包
apt-get dist-upgrade # ---------升级系统
apt-get dselect-upgrade #------使用 dselect 升级
apt-cache depends #-------(package 了解使用依赖)
apt-cache rdepends # ------(package 了解某个具体的依赖,当是查看该包被哪些包依赖吧...)
apt-get build-dep # ------(package 安装相关的编译环境)
apt-get source #------(package 下载该包的源代码)
apt-get clean && apt-get autoclean # --------清理下载文件的存档 && 只清理过时的包
apt-get check #-------检查是否有损坏的依赖
dpkg -S filename -----查找filename属于哪个软件包
apt-file search filename -----查找filename属于哪个软件包
apt-file list packagename -----列出软件包的内容
apt-file update --更新apt-file的数据库

dpkg --info "软件包名" --列出软件包解包后的包名称.
dpkg -l --列出当前系统中所有的包.可以和参数less一起使用在分屏查看. (类似于rpm -qa)
dpkg -l |grep -i "软件包名" --查看系统中与"软件包名"相关联的包.
dpkg -s 查询已安装的包的详细信息.
dpkg -L 查询系统中已安装的软件包所安装的位置. (类似于rpm -ql)
dpkg -S 查询系统中某个文件属于哪个软件包. (类似于rpm -qf)
dpkg -I 查询deb包的详细信息,在一个软件包下载到本地之后看看用不用安装(看一下呗).
dpkg -i 手动安装软件包(这个命令并不能解决软件包之前的依赖性问题),如果在安装某一个软件包的时候遇到了软件依赖的问题,可以用apt-get -f install在解决信赖性这个问题.
dpkg -r 卸载软件包.不是完全的卸载,它的配置文件还存在.
dpkg -P 全部卸载(但是还是不能解决软件包的依赖性的问题)
dpkg -reconfigure 重新配置

摘自 http://qiuye.iteye.com/blog/461394
** 测试端口是否打开
telnet 192.168.1.103 80
** 查看服务名servers
service --status-all
** 修改root密码
: sudo passwd root
使用
su root
** apt安装的包查询
dpkg -l gitlab-ce
** boot磁盘满
sudo du -h /boot
sudo apt-get remove linux-image-    tab键
http://blog.csdn.net/wxyangid/article/details/53097208

** 壁纸
http://www.lovebizhi.com/

Ubuntu安装Variety
$ sudo add-apt-repository ppa:peterlevi/ppa
$ sudo apt-get update
$ sudo apt-get install variety

** apt彻底删除 
彻底删除 sudo apt purge 
** 提示/var/目录空间不够
   sudo mv /var/cache/apt/archives/* ~/Desktop/newfold
** ubuntu开机自动启动设置
如果只是想开机时执行一些命令在背景运行, 而不是用到复杂的开机服务(例如可以暂停重启什么功能的), 可以这么做:
  - 编辑/etc/rc.local, 在 exit 0 前面加入你要执行的命令,脚本. 注意, 这个是很早的执行阶段, 可能PATH没有设置好, 所以最好用绝对路径!!!再说一次, 绝对路径! 包括脚本内!
  - sudo crontab -e 进入计划事务编辑模式, 编辑计划, 加入这么一句@reboot /path/to/script. 这个可以加载比较多的指令了, 如果没有正常运行, 请用绝对路径.
  - 如果要执行的命令没有背景运行模式, 可以用nohup command > /dev/null 2>&1 &
一般的开机服务是定义在/etc/init.d里的东东, 图形管理界面可以使用sysv-rc-conf, 命令行可以使用service命令.
** unbuntu加快开机速度
  :systemd-analyze blame
查看到
         33.587s NetworkManager-wait-online.service
         21.164s docker.service
          8.088s mysql.service
          5.018s plymouth-start.service
         ...
执行
   :sudo systemctl disable NetworkManager-wait-online.service
   :sudo systemctl disable docker.service
参考
http://www.jianshu.com/p/11491ee15344
* 如何为sudo命令定义PATH环境变量
添加所需要的路径(如 /usr/local/bin）到"secure_path"下，在开篇所遇见的问题就将迎刃而解。
Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
http://www.linuxidc.com/Linux/2014-09/106076.htm

* node ubuntu安装
sudo apt install 的版本太旧

cd /usr/local/src
搜索nodejs镜像
sudo wget https://npm.taobao.org/mirrors/node/v6.11.0/node-v6.11.0-linux-x64.tar.gz
tar zxvf
mv node... node
cd
vim ~/.bashrc
export  PATH=/usr/local/node/bin:$PATH

source .bashrc


命令行工具 cnpm
还可以通过定制的 cnpm 命令来直接从淘宝镜像源安装模块，参考 https://npm.taobao.org/
# 安装 cnpm
npm install -g cnpm --registry=https://registry.npm.taobao.org
# 通过 cnpm 命令替代 npm 命令安装模块
cnpm install express
参考 https://blog.niceue.com/front-end-development/using-domestic-npm-images.html

* Ubuntu vim emacs 翻译工具安装
安装ui版 sudo apt install stardict
  安装本地词典 http://download.huzheng.org/
  tar -xjvf star....tar.bz2 -C /usr/share/stardict/dic
安装命令行版 sudo apt install sdcv 


支持vim翻译
  ~/.vim/plugin/sdcv.vim
    
function! Mydict()
  "执行sdcv命令查询单词的含义,返回的值保存在expl变量中
  let expl=system('sdcv -n ' . expand("<cword>"))
  "在每个窗口中执行命令，判断窗口中的文件名是否是dict-tmp，如果是，强制关闭
  windo if expand("%")=="dict-tmp" |q!|endif	
  "纵向分割窗口，宽度为25，新窗口的内容为dict-tmp文件的内容
  25vsp dict-tmp
  "设置查询结果窗口的属性，不缓存，不保留交换文件
  setlocal buftype=nofile bufhidden=hide noswapfile
  "将expl的内容显示到查询结果窗口
  1s/^/\=expl/
  "跳转回文本窗口
  wincmd p
endfunction
"按键绑定，将调用函数并执行
nmap F :call Mydict()<CR>


用法：
  非编辑模式下 调用 shift + f
  退出 C-w o

man 模式下 !sdcv hello

参考http://renwolang521.iteye.com/blog/1317789
    http://blog.codepiano.com/2012/03/24/translate-word-under-cursor-in-vim

支持emacs
;; author: pluskid
;; 调用 stardict 的命令行接口来查辞典
;; 如果选中了 region 就查询 region 的内容，
;; 否则就查询当前光标所在的词
(global-set-key [mouse-3] 'kid-star-dict);;鼠标右键
(defun kid-star-dict ()
  (interactive)
  (let ((begin (point-min))
        (end (point-max)))
    (if mark-active
        (setq begin (region-beginning)
              end (region-end))
      (save-excursion
        (backward-word)
        (mark-word)
        (setq begin (region-beginning)
              end (region-end))))
    ;; 有时候 stardict 会很慢，所以在回显区显示一点东西
    ;; 以免觉得 Emacs 在干什么其他奇怪的事情。
    (message "searching for %s ..." (buffer-substring begin end))
    (tooltip-show 
     (shell-command-to-string 
      (concat "sdcv -n " 
              (buffer-substring begin end))))))

* 翻墙 ubuntu shadowsocks
# http://blog.csdn.net/wf632856695/article/details/72819402
更新软件源
apt-get update
安装pip环境
apt-get install python-pip
安装shadowsocks
pip install shadowsocks
此时，如果出现了提示版本太低，则按照提示更新
pip install --upgrade pip

解决pip install 时locale.Error: unsupported locale setting
# http://blog.csdn.net/qq_33232071/article/details/51108062
export LC_ALL=C

如果提示没有setuptools模块，则安装setuptools
pip install setuptools

如果刚才shadowsocks安装成功则跳过这一步，某则继续安装shadowsocks
pip install shadowsocks
编辑配置文件
vim /etc/shadowsocks.json
添加：

{
    "server":"45.76.157.31",
    "server_port":8388,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"flzx3qc",
    "timeout":300,
    "method":"aes-256-cfb"
}



name	info
server	服务器 IP (IPv4/IPv6)，注意这也将是服务端监听的 IP 地址
server_port	服务器端口
local_port	本地端端口
password	用来加密的密码
timeout	超时时间（秒）
method	加密方法，可选择 “bf-cfb”, “aes-256-cfb”, “des-cfb”, “rc4″, 等等。默认是一种不安全的加密，推荐用 “aes-256-cfb”

赋予文件权限
chmod 755 /etc/shadowsocks.json

# 安装以支持这些加密方式
# apt-get install python–m2crypto

后台运行
ssserver -c /etc/shadowsocks.json -d start

停止命令
ssserver -c /etc/shadowsocks.json -d stop

设置开机自启动
vim /etc/rc.local
加上如下命令：

#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.
ssserver -c /etc/shadowsocks.json -d start
exit 0

手机端
v4.2.5
https://github.com/shadowsocks/shadowsocks-android/releases/download/v4.2.5/shadowsocks-nightly-4.2.5.apk
* vultr
<2018-01-12 五> shadowsocks无法工作，重启后无效 
决定重换服务器,竟然$2.5/mon 的售完了...
东京主机 打不了 ”| “符号，连不了ssh服务
换了新加坡服务器问题解决
** 调试记录
<2017-12-20 三> 无法链接到外网，重启=ssserver -c /etc/shadowsocks.json -d start=后生效
* aws Amazon Web Service 
*login in and setup*
my secret key file is saved on
: ~/aws.pem
Login in
: ssh -i "ec2.pem" ubuntu@ec2-54-200-248-155.us-west-2.compute.amazonaws.com
or
: ssh -i ec2.pem ubuntu@hostname

After login
Follow the promot
#+BEGIN_QUOTE
WARNING! Your environment specifies an invalid locale.
 The unknown environment variables are:
   LC_CTYPE=zh_CN.UTF-8 LC_ALL=
 This can affect your user experience significantly, including the
 ability to manage packages. You may install the locales by running:

   sudo apt-get install language-pack-zh
     or
   sudo locale-gen zh_CN.UTF-8
#+END_QUOTE

: sudo locale-gen zh_CN.UTF-8

*ping not work*

https://www.zhihu.com/question/30711594 aws上已部署好服务器，为什么弹性IP还是ping不通？

选择左边菜单  网络与安全 ---》安全组---》对应的安全组  选择入站规则---》再编辑
添加新的入站规则
   选择允许全部流量

然后选择 实例-》操作-》联网-》更改安全组
                        -》管理ip地址可查看ip    
然后就可以ping通了


*install shadowsocks*

: sudo apt-get install python-pip
: sudo pip install shadowsocks
: sudo vim /etc/shadowsocks.json

{
    "server":"0.0.0.0",
    "server_port":8388,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"flzx3qc",
    "timeout":300,
    "method":"aes-256-cfb"
}

赋予文件权限
: chmod 755 /etc/shadowsocks.json

后台运行
: ssserver -c /etc/shadowsocks.json -d start

tips: when option "server" is set to real ip,shadowsocks can't be correct install
After
: ssserver -c /etc/shadowsocks.json -d start
Then use stop momand prompt messege ssserver isn't started

*Update*
Can't connect to aws ec2 <2018-01-13 六>
https://www.zhihu.com/question/21271342 亚马逊的AWS不能SSH登录了怎么办？
参考"把security group删了重新加一个呢？"回答，删了安全组，重新添加了一遍。发现了问题所在，也是上一次配置安全组时给自己留的坑，入站位置设为了只有本机。当第二天打开本地电脑时本地ip变了，所以连不上了
解决：安全组入站限制改为允许所有位置，这样也同时解决了手机端链接shadowsocks的问题


* 工具
** 命令行打开文件管理器
nautilus /etc
** 内网穿透
http://www.ittun.com/ 
** ftp
filezilla
   
** zip unzip 压缩解压中文
: unzip -O cp936 UE.zip  # 解决解压乱码
: unzip file.zip -d destination_folder

: zip -r fold.zip fold  # 压缩文件
: zip -e file.zip file  # 加密文件
** 从window拷贝代码到ubuntu（linux）乱码问题解决
: iconv -f GBK -t UTF-8 bbbb.txt -o bbbb.txt
有时转码后依然会出现乱码，可以利用iconv的参数-c，忽略输出的非法字符，就可以了。
: iconv -f GBK  -t UTF-8 -c leach.m > leach1.m
http://blog.csdn.net/u010126792/article/details/61616884
** pdf->doc
http://pdf2doc.com/zh/
** 花瓶抓包
** 后台模板
Metronic

* 方
** 症
畏寒 走一段路腿疼
不渴
胸闷气短
** 开方
黄芩泻白散合黛蛤散

黄岑10克 桑白皮15克  地骨皮15克  粳米15克   
麦冬10克 北沙参10克 栀子5克 郁金3克 柴胡3克 甘草3克  

http://yibian.hopto.org/fang/?fno=204
http://www.baike.com/wiki/%E9%BB%9B%E8%9B%A4%E6%95%A3
http://www.zysj.com.cn/zhongyaocai/yaocai_z/zhizi.html

http://www.360doc.com/content/15/0702/05/6851991_482048129.shtml

黛蚵散比例
黛蛤散中海蛤壳性味咸寒，可清热化痰、软坚散结，青黛性味咸寒，可清热解毒，凉血定惊，故合用可治疗肝火犯肺，
咳痰带血，咽喉不适等症状，对咳嗽时间比较长，并且痰黏不容易咳出来者尤为有效。一般蛤粉与青黛的配伍比例为10︰1，
热象重者青黛可以酌加，散剂每服3~6g，日服2~3次，煎剂10~30g，儿童酌减。脾胃虚寒者慎用。我的体会直接吞服散剂较煎剂效佳
http://blog.sina.com.cn/s/blog_58d372a70102vuoe.html

-- 小青龙汤 记得李可老中医 用此方加减来治慢性肺病

参考 祛湿利水经典方剂五苓散 https://mp.weixin.qq.com/s?__biz=MzA5ODM0ODgzMA==&mid=2651213214&idx=1&sn=a5feb911b725a4f2369df0143f8a871f&pass_ticket=YTrv83NFiSc592lZ4Vac%2B7lzpE6qjykYG627dLTfZfMh2ZJvyaZ2wZy9w2NunkQV

三、胃苓汤（《丹溪心法》）为五苓散与平胃散（陈皮、厚朴、苍术、甘草）的合方，利水祛湿剂与芳香化湿剂合用，除加强祛湿作用外，还着重加强行气化气作用，适用于脾湿气滞、消化不良、脘腹胀痛泄泻、小便短少者。

查厚朴 
http://yibian.hopto.org/yao/?yno=241 
痰飲喘咳。本品能燥濕化痰，下氣平喘。對於宿有喘病，因外感風寒而發者，可與桂枝、杏仁等同用，如桂枝加厚朴杏子湯；若痰濕內阻，胸悶喘咳者，常與蘇子、橘皮等同用，如蘇子降氣湯。

内科不治喘，治喘丢了脸——经方泰斗胡希恕治哮喘经验总结 http://mp.weixin.qq.com/s/49GHtxN3ZEfhgTkQ-uRl2Q

从六经辨证来看，哮喘常表现为太阳病或少阳病，尤以太阳少阳并病、少阳阳明并病和三阳并病为最多见，而且以实证为多见。中医所说的哮喘，一般多是指临床上的一个症状，以邪气实多见。

大柴胡汤合桂枝茯苓丸方证主症见：胸胁苦满，呼吸困难，心下急，口苦咽千，大便干燥。

少阳病 https://zh.wikipedia.org/wiki/%E5%B0%91%E9%99%BD%E7%97%85
查得 变证 阴阳升降失常，上热下寒证：黄连汤 http://yibian.hopto.org/fang/?fno=95
【辨證要點】
胸中煩熱。
腹中冷痛。
嘔吐下利腸鳴。
苔白膩。
脈弦。

黃連9克  甘草9克  乾薑9克  桂枝9克  人參6克  半夏12克  大棗4枚 

郝万山讲《伤寒论》 第38讲 http://www.theqi.com/simplified/cmed/class/class1/note_38.html
如果全身的表现是无汗的，还可以用麻黄汤，就是完全是寒邪闭郁了阳明经表的阳气，全身表现为无汗，而额头疼痛，缘缘面赤，目痛鼻干，这种症状又不特别突出，那就用麻黄汤

麻黄汤 http://yibian.hopto.org/shu/?sid=603
发汗猛 暂不用

大柴胡湯	 http://yibian.hopto.org/fang/?fno=10

柴胡15克(8兩)  黃芩9克(3兩)  半夏9克(半升) 洗  枳實9克(4枚) 炙  大黃6克(2兩)  芍藥9克(3兩)  生薑15克(5兩) 切  大棗12枚 擘  
右七味，以水一斗二升，煮取六升，去滓再煎，溫服一升，日三服

桂枝茯苓丸 http://yibian.hopto.org/fang/?fno=165
桂枝10克  茯苓10克  牡丹皮10克  白芍10克  桃仁10克  

[经典] 黄煌 大柴胡汤的方证及其现代应用 http://blog.sina.com.cn/s/blog_73b391c60102very.html
先说说大柴胡汤的配方，比起当下一些中医开的方，大柴胡汤算是个小方了，共八味药。柴胡半斤、黄芩三两、半夏半升、枳实四枚、芍药三两、大黄二两，生姜五两、大枣十二枚，以水一斗二升，煮取六升，去滓，再煎。温服一升，日三服。这里有几点说明一下：
柴胡半斤，就是八两，如果按一两等于3克折算，应该24克，如果一两等于5克折算，也应该40克，显然，用柴胡5克10克的，可能算不上大柴胡汤；
 
半夏半升：经推测，半夏一升为五两，半升为二两半，可折算为12.5克，我多用10-15克。
 
枳实四枚：汉代没有枳壳枳实之分，后来将小嫩的果实为枳实，大的为枳壳。这个说法，在宋代沈括《梦溪笔谈》中已经提及。根据实测，一枚枳实重约3克，一枚枳壳重量约为枳实的3-5倍，甚至更多，所以，原方用4枚枳实，可能重量当在40克以上，甚至到80克。提示我们现在用量比较保守，可以摸索大剂量枳实枳壳应用的经验

郝万山讲《伤寒论》
第21讲 太阳蓄血证（1） http://www.theqi.com/cmed/class/class1/note_21.html
大柴胡汤证是上腹部满痛，大承气汤证是脐周极其胀满有力，桃核承气汤证是下腹部压痛。

原来有血管瘤，现在怎么没有呢？对照起来，前后差了半年，就是没有了。他就问怎么治疗的？她说我就是找一个中医大夫，一直吃一种胶囊治好的，但是从那时候到现在，用抵当汤做成散剂治疗脑血管瘤，有这么好的效果的我只遇到这么一例，后来我遇到类似的病人，我也用过，也许是病人在坚持吃药方面，有些困难

“太阳病身黄”，这个身黄，可以见于太阳蓄水，也可以见于太阳蓄血，太阳蓄血，血热互结，阻滞气机，而全身的气机是靠肝胆来疏泄的，血热互结，阻滞气机，气机阻滞以后，就容易反过来影响肝胆疏泄，

是蓄血的，你可以用抵当汤来治疗。这一条特别强调了蓄水和蓄血的区别，在于小便利和小便不利

大柴胡湯 用量 http://www.tcmforum.com/forum2.php?forumID=100483&fGroup=expert

按之心下滿痛者，此為實也，當下之，宜大柴胡湯”。細與《傷寒論》條文對照，可知大柴胡湯證不必非是由太陽而少陽陽明，也可以是雜病獨立的病證。心下者，心之下也，不僅包括胃，也包括肝膽和胰，按之滿痛是點明的主證，其它尚有發熱口燥、惡心、嘔吐、尿赤、大便乾結，或黃疸、胸脅滿痛，舌必紅，苔必黃，脈必沉實滑數。

不過需要指出，在急腹症的治療中，因邪實是主要矛盾，故藥量宜大，如柴胡常用至30克，黃芩15克，大黃30~40克，白芍25克，枳實(或枳殼)15~20克，使藥能勝病，邪去而元氣自復

桃核承氣湯	http://yibian.hopto.org/fang/?fno=161

经方一百首

067、桃核承气汤 与、抵当汤、桂枝茯苓区别
http://www.tcm100.com/user/jfybs/zzbook67.htm
本方与桂枝茯苓丸都有少腹疼痛拒按的瘀血证候、但本方有明显的精神症状，表现小躁、狂、烦的外在征象，是瘀血初聚结；桂枝茯苓丸证偏向于—种安静的状态，瘀血瘀积已久，形成有限范围的癥块。
龙野一雄曾把桃核承气汤、抵当汤、桂枝茯苓丸在腹证进行了详细区别。此三者在腹诊上必须非常熟练才能鉴别。其要点如下：三者的抵抗位置皆无特征，随处可以发现一至数处。
而抵当汤证的抵抗在深部，且略有硬感，无腹动。桂枝茯苓丸证的抵抗亦在深部有硬感，境界多相当明显，亦有成为硬结者，多能证明髂总动脉的紧张、压痛，搏动亢进。桃核承气汤证之抵抗略软，境界多不明显，
虽有髂动脉的紧张和压痛，不一定有搏动亢进的现象，但可见少腹急结。桃核承气汤的加味药多为蒲黄、当归、牛膝、乌药等。本方证病在下焦，故其服法仲景条文提出“先食温服”，以使药力直达病所，迅速发挥逐瘀下行之力。临床使用时多嘱咐病人在饭前1小时空腹服药，应注意

脾陽虛主要是怕冷脾氣虛主要是無力 http://chenron.pixnet.net/blog/post/351714137-%E8%84%BE%E9%99%BD%E8%99%9B%E4%B8%BB%E8%A6%81%E6%98%AF%E6%80%95%E5%86%B7-%E8%84%BE%E6%B0%A3%E8%99%9B%E4%B8%BB%E8%A6%81%E6%98%AF%E7%84%A1%E5%8A%9B
附子理中湯	  	來源	
http://yibian.hopto.org/fang/?fno=691
【辨證要點】

腹痛不渴。
或嘔或利。
四肢厥冷。
舌淡苔白。
脈沈遲。

症：有10年左右，一月二三次，尿痛，不利，严重时带血
清利下焦湿热重在健脾胃https://www.douban.com/note/89856731/

清利湿热的过程中易伤及正气，利湿易伤阴，清热则易伤阳，滋阴则易助温，温阳则热易生，所以说临床要仔细把握这对矛盾的相互性，
合理地分析湿热和正虚的关系，制订下科学的治疗法则，才能聚集较好的疗效。

脾胃的正常功能的发挥，不仅能源源不断地提供后天之精，而且重要的运化水湿，疏通经脉， 脾健则湿无所生，湿无生则热无以合，
故湿热难成，故在清利湿热，尤其是在清利下焦湿热之症时，健脾是非常重要的，同时还需要提及一点，脾易受肝之所制，故少佐调肝之药，效更佳。

2007/08/29
症：上一周左右因为鼻窦炎头疼，前两天血压测了偏高，今晚测血压偏高，这两周有些胸闷，这两天有轻微的咳嗽的症状
开方：用黛蚵散配活血散淤

青黛10g 海蚵壳10克  柴胡10g 香附6g  川芎6g 桂枝10g  黃芩10g 枳壳 10g 桃仁6g  生姜6g 野菊花10g 夏枯草10g 辛夷6g 甘草10g 炙甘草6g 苍术6g 红枣3枚  

黄连
http://yibian.hopto.org/yao/?yno=100
本品兼清肝火，若肝火犯胃，肝胃不和，脇肋脹痛、嘔吐吞酸，可與吳茱萸同用，如左金丸

香附 http://yibian.hopto.org/yao/?yno=152
與柴胡、川芎、枳殼等同用，如柴胡疏肝散

止嗽散	http://yibian.hopto.org/fang/?fno=238

2017/08/04
血府逐瘀汤 
http://yibian.hopto.org/diag/syp.php?sypno=178 
当归三钱（9克），生地黄三钱（9克），桃仁四钱（12克），红花三钱（9克）、枳壳二钱（6克），赤芍二钱（6克）、柴胡一钱（3克），甘草二钱（6克），桔梗一钱半（5克），川芎一钱半（5克），牛膝三钱（9克） + 夏枯草6克  菊花6克

2017-11-15
大柴胡汤+桂枝茯苓+血府逐淤汤 + 黄连 治咳嗽高血压失眠
http://www.cqvip.com/read/read.aspx?id=41221245
柴胡30克，黃芩15克，大黃30克，白芍25克，枳實15克 半夏15克 生姜6克 大枣3枚  桂枝10克  茯苓10克  牡丹皮10克  桃仁10克 黄莲6克



